### ISSUE TITLE
Custom DAP code gives google-analytics.com unfettered control of USG websites

### ISSUE THREAD

**Issue by fulldecent** [digital-analytics-program/gov-wide-code#61]
I have reviewed the current implementation that participating websites are using, I believe the latest version is posted at https://github.com/digital-analytics-program/gov-wide-code/blob/e2ebbbff99d4875b74966b38eff33599371fd1e1/Universal-Federated-Analytics.js

The largest vulnerability you have is in these lines: https://github.com/digital-analytics-program/gov-wide-code/blob/e2ebbbff99d4875b74966b38eff33599371fd1e1/Universal-Federated-Analytics.js#L532-L536

This is unmodified from Google's original ISOGRAM code. However, this fails to include a a.crossorigin = 'anonymous' line which is best practice. Additionally, any security audit you have performed is invalid because a. \integrity is not specified. Therefore google-analytics.com has the unfettered ability to inject arbitrary code or modify the contents of any US government web page.

This is a common practice on the web today, but it is not best practice. Because you are recommending a policy for ALL US government websites your standards should be higher.

I have reported this issue to dap@support.digitalgov.gov, but I have opened primary discussion of this issue here on GitHub where the most relevant audience may find it.

# Work plan

- [ ] Add `a.crossorigin = 'anonymous'` to the recommended DAP code
- [ ] Better document the risks that the DAP code has w/r/t google-analytics.com and google.com
- [ ] Adopt SRI for Google Analytics, by adopting one of the following
  * Renegotiate with Google, have them host a versioned copy of the file which can be reviewed and hashed, link to that file
  * Copy or "closely reimplement" the Google Analytics script and host on common GSA servers, link to that file
  * Copy or "closely reimplement" the Google Analytics script and host it on every DAP program participant

**Comment by tdlowden** [comment]
Thanks for this @fulldecent! We are investigating and will keep you updated here.

**Comment by konklone** [comment]
> Additionally, any security audit you have performed is invalid because a. \integrity is not specified. 

Can you be more specific? Do you mean using [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) or something else?

In any case, Google makes no guarantees about its JS code remaining snapshotted to particular versions -- there's no single hash we could pin the content to, and that's not likely to be a supported function any time soon.

> Therefore google-analytics.com has the unfettered ability to inject arbitrary code or modify the contents of any US government web page.

This is likely to remain the case under any implementation of Google Analytics, and is a risk that is accepted by any participating agency. 

This is also one of the reasons that this JavaScript is not encouraged for use inside authenticated sessions. 

You can see an example of a government project (login.gov) considering these risks and preventing DAP from posing a risk to authenticated sessions here: [1](https://github.com/18F/identity-idp/pull/1257), [2](https://github.com/18F/identity-idp/pull/1263), [3](https://github.com/18F/identity-idp/pull/1288).

As you say, there are very real risks associated with the use of third party services on the web, common as they may be. You may find useful some of the work 18F has done to detect these things at scale using headless browsers: https://github.com/18F/domain-scan/pull/107

But yes, depending on the integrity of google-analytics.com for unauthenticated sessions is a known and accepted practice here, and there isn't an obvious way I'm aware of for the project to mitigate this risk.

> However, this fails to include a a.crossorigin = 'anonymous' line which is best practice.

This is probably an easy addition, but can you note any particularized impact here? This would only affect credentials that are relevant to communication with the origin `dap.digitalgov.gov`, and I don't believe any cookies, client certificates, or basic auth credentials would ever be associated with that origin. So, there should be no current risk here -- but yes, it is good hygiene and probably easy to add with no risks associated with doing so.

**Comment by fulldecent** [comment]
@konklone thank you for these points and analysis. I'll stay on topic and address each item here as it relates to issue #61

* Yes, this is regarding **Subresource Integrity**

* True, Google has failed to make any assurances regarding this code (i.e. that it wont change). True, Google is unlikely to make assurances regarding this code unless they are required to. GSA, as a very large Google client, is uniquely positioned to negotiate such a clause.

* *Any implementation of Google Analytics will be vulnerable.* One implementation that removes this risk is to copy https://google-analytics.com/analytics.js to https://dap.digitalgov.gov/analytics-2017-09-13.js. I have added this and other options at the top of this issue under WORK PLAN.

* *This is also one of the reasons that this JavaScript is not encouraged for use inside authenticated sessions.* That's not good enough. Any page that has a "login" link on it is vulnerable to having that login link modified to point somewhere else. Case in point, see the next bullet here...

* login.gov has poorly implemented security w/r/t Google Analytics

   The page https://login.gov/ includes a resource from Google that is identified only by URL. Therefore, Google has full permission and authority to modify this page as it sees fit. This includes modifying the login link ("manage my account") to point somewhere else\

    For an only slightly less secure example, see http://www.dcaa.mil/hotline/ which states "DCAA Hotline can only accept UNCLASSIFIED complaints on this website." This page can also be modified in transit and without leaving any evidence of tampering. Just s/UNCLASSIFIED/CLASSIFIED/ for results. (I've discussed with the Office Inspector General about this years ago, still not fixed, here's a first public disclosure of that.)

    Issue https://github.com/18F/identity-idp/pull/1257 is discussed but I don't think they implemented it because https://secure.login.gov/ still includes analytics.

* *`a.crossorigin = 'anonymous'` This is probably an easy addition, but can you note any particularized impact here?* Good question, I have raised it to smarter people than me at https://stackoverflow.com/q/46209817/300224

----

Here are a few more things everyone probably knows, but are very relevant and should be mentioned.

* **Google is hackable.** The public knows that Google has been [infiltrated by the US National Security Agency](https://archive.org/details/NSA_Powerpoint_Slide_-_Google_Cloud_Exploitation)  (warning link is TS//SI) and has also [had its accounts compromised in China](http://www.reuters.com/article/us-google-hacking/google-reveals-gmail-hacking-says-likely-from-china-idUSTRE7506U320110602). How many ways has or will Google be compromised that the public does not know about?

* **You won't know if you've been hacked.** A successful compromise of google-analytics.com, or other sites that are included by reference, will likely leave zero evidence of compromise on the victim's computer and on parties monitoring the network.

**Comment by konklone** [comment]
> True, Google has failed to make any assurances regarding this code (i.e. that it wont change). True, Google is unlikely to make assurances regarding this code unless they are required to. GSA, as a very large Google client, is uniquely positioned to negotiate such a clause.

This is unlikely to be practical for Google, and is the opposite of the direction they (and we) would be likely to go. While the DAP could make use of snapshotted URLs by updating its link to GA in each snapshot of the DAP code, this sort of use of GA is extremely rare. Overwhelmingly, GA is used by administrators dropping in the embed code and never touching it again. 

This is a **good thing** for the security of the GA ecosystem, because privacy and security fixes get distributed immediately to the entire population. DAP, though one layer removed, has the exact same problem -- when the only option for agencies was self-hosting, it was impossible for DAP to distribute security- and privacy-relevant fixes, and rot across the ecosystem overall reduced user security.

This is one of the reasons why dap.digitalgov.gov was created as central hosting, and it has the same dynamic you outline for GA. Agencies would potentially be more secure from compromise of **our** servers by either self-hosting, or by the DAP committing to snapshots and providing SRI hashes. However, this would paralyze the ecosystem and defeat the benefits of central hosting.

I do understand the security issue you are pointing out, but there are larger, ecosystemic security issues to weigh, and SRI is in fundamental tension with the principle of automatic updates across a deployed ecosystem -- a fundamental tenet of maintaining secure clients. 

SRI is far more practical when there's a small/single number of groups of people maintaining the surface area of SRI hashes and overall dependency updates. In a distributed ecosystem, it's unlikely to make sense -- either for DAP, or for Google.

> The page https://login.gov/ includes a resource from Google that is identified only by URL. Therefore, Google has full permission and authority to modify this page as it sees fit. 

Yes, this is understood and accepted.

> Issue 18F/identity-idp#1257 is discussed but I don't think they implemented it because https://secure.login.gov/ still includes analytics.

The pull request, which says to use DAP when the user is fully logged out, was implemented. DAP is only present on the login page, where the user is fully logged out.

The rest of the app, even when logged in, continues to use _their own_ Google Analytics account (not connected to DAP). So yes, the team currently accepts the risk of Google Analytics inside the authenticated environment.

@tdlowden I recommend this issue be closed, as I don't believe there's anything that DAP can feasibly do about the issues raised here, for the reasons explained above. (If the DAP team wants to do `crossorigin=anonymous`, that would probably function best as a separate issue at this point.)

On a personal note, @fulldecent, while I share your concerns about overreliance on, and underawareness of the dangers of, Google Analytics across the internet, I think the issue has be to be handled at another layer. DAP would be well-served to reduce its own reliance on Google Analytics and to explore other alternatives, but if GA is going to be used, then the risk here just has to be accepted. If you've got a passion for removing unnecessary third party dependencies that aren't as critical to business success as Google Analytics, I suggest taking a look at https://github.com/18F/domain-scan/pull/107 and finding other third party services which could easily be eliminated from .gov services. There are many!

**Comment by fulldecent** [comment]
Thank you for the discussion here. I believe this issue has been duly acknowledged and accepted as a risk here. As to whether this risk is properly documented and disclosed to government users, that can be discussed at https://github.com/digital-analytics-program/gov-wide-code/issues/60. I can't access that document so I can't comment further now.

Per your notes, a requirement for this program is *to get security updates from Google* and *to make DAP users get these updates automatically*. The only practical decision is:

1. **Continue as is.**
   * DAP users (i.e. every US government website) remain vulnerable to a compromise of google.com or google-analytics.com or intentional actions by/on behalf of Google.
   * Every DAP user will receive security updates from Google.
   * Zero maintenance effort is required for DAP users get the updates.
   * Google pays the cost of serving the analytics.js file.
2. **Host analytics.js from GSA servers (do not use SRI).**
   * Every US government website is vulnerable to a compromise of the central GSA server.
   * GSA will review and timely deploy updates of analytics.js to GSA servers.
   * Zero maintenance effort is required for DAP users get the updates.
   * GSA pays the cost of serving the analytics.js file.

The decision is only a matter of: *should Google or GSA be trusted to serve this important file?* and *what is the additional cost for GSA to serve this file?*

I think this dichotomy is clear to everyone here. If option \#2 is not viable then I will accept that this decision can be closed. However it may be helpful to explicitly document what the cost is for GSA to host this analytics.js file. And it should be helpful to document how GSA has decided that google.com and google-analytics.com is an acceptable risk. Why? see below...

---

@konklone thanks for sharing, I will check out that 18F project. They are a nice team, and I've been involved in some of their other projects.

The discussion here in #61 is an important starting point because surely there are other hosted javascript files which, by default, can take complete control of your website. The same arguments used here can easily be used to promote keeping status quo:

* We don't currently use SRI.
* If we implement SRI we lose security updates from the vendor and updates must be manually deployed.
* Everybody wants security updates, right?

Those arguments apply to EVERY hosted javascript file:

* connect.facebook.net/en_US/all.js [doesn't use SRI](https://developers.facebook.com/docs/javascript/quickstart/)
* visistat.com [doesn't use SRI](http://id.kickfire.com/tracking-tag.php?key=skk0BVzBjzbKc)
* weibo.cn [doesn't use SRI](http://open.weibo.com/wiki/2/oauth2/authorize/en)
* 20script.ir [doesn't use SRI](http://www.20script.ir/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%DA%AF%D9%88%DA%AF%D9%84-%D8%A2%D9%86%D8%A7%D9%84%DB%8C%D8%AA%DB%8C%DA%A9%D8%B3-google-analytics/)

Before we trust a random website in Iran (hint: they don't all end in `.ir`) to provide security updates, it will be helpful to have our thorough and critical review of Google as a starting point.

**Comment by konklone** [comment]
> The decision is only a matter of: should Google or GSA be trusted to serve this important file? and what is the additional cost for GSA to serve this file?

GSA hosting snapshots of `analytics.js` and regularly manually reviewing changes is an option, but unfortunately, due to how `analytics.js` is implemented by Google, I don't think it is a viable one. Here's what the JS looks like:

https://www.google-analytics.com/analytics.js

<img width="954" alt="screen shot 2017-09-21 at 12 54 53 pm" src="https://user-images.githubusercontent.com/4592/30708223-13d0022a-9ecc-11e7-9da2-3d06f386f22e.png">

The code is minimized and obscured by Google. Google doesn't provide a reference unminified version (with steps on how to minify it and validate that the minified version is the same as the unminified one), or a changelog, or anything that would allow a team to reasonably review changes to this JavaScript. 

While we could make a best-effort job to reverse engineer the JavaScript, I think the practical ability for us to distinguish legitimate changes from malicious changes would be extremely limited and unlikely to be worth the effort. I also think Google is unlikely to be persuaded to begin explaining each change to the code, or provide an unminified reference version, as this is core proprietary code to a proprietary system.

> The discussion here in #61 is an important starting point because surely there are other hosted javascript files which, by default, can take complete control of your website. The same arguments used here can easily be used to promote keeping status quo...

Unfortunately, that's right -- and that's why I think SRI is significantly oversold as a security mechanism. SRI can reasonably be deployed for high-value includes, where the included asset is actually managed by the same entity but hosted on separate infrastructure, or where it is possible and worthwhile for a team to review each update and keep the SRI hashes fresh.

For example, GitHub uses SRI on this page we're talking on right now to guarantee that their CDN is not compromised:

```
<link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-794ddde646dd1791582965df2f5d1936d07f155e9fb08f86df99a2043d48408a.css" integrity="sha256-eU3d5kbdF5FYKWXfL10ZNtB/FV6fsI+G35miBD1IQIo=" media="all" rel="stylesheet" />
```

That makes tons of sense for GitHub, as it's core to their security posture and they're in a position to review changes (or even automate this based on their overall deployment pipeline). 

But yes, for most small teams whose apps pull in third-party services via JS, SRI is unlikely to be adoptable for them. I typically try to encourage folks to inline wherever they can (for example, hosting `jquery.js` themselves rather than hot-linking to `code.jquery.com`, or by [inlining Google Fonts](https://github.com/18F/18f.gsa.gov/pull/672)), but I would have a hard time arguing to most website owners (especially those who are not very technical) that they should employ SRI on all the third party services they use for the reasons we discussed.

There is a proposal to have SRI operate via signature, rather than hash, which would allow third parties to update JS in place as long as the team continues to sign using the right key. There are other concerns about this approach being a footgun or dangerous, as key roll-over (as a result of key loss or compromise) could suddenly lead to massive breakages.

The web definitely has some severe problems in this area, and I wish there were more we could reasonably do about them here, especially for a program like DAP. I'm certainly open to discussing more ideas. Thank you for elevating this issue here, and I think we've been able to produce a useful public discussion that others can learn from.

**Comment by fulldecent** [comment]
It is not necessary to disassemble and reverse engineer analytics.js. Instead you can just confirm that the version Google is serving you matches what your web visitors get. This is a very economical "review" that protects against the most likely and least detectable type of attack.

In other words, I can run `curl 'https://www.google-analytics.com/analytics.js' | shasum` and that gives:

> d5739f7e215acb3b89da9431d9da35cb73e0271f

I hope you get the same result. I tested with `curl` and Chrome user agents and they produced the same result.

This is my intention for \#2 in https://github.com/digital-analytics-program/gov-wide-code/issues/61#issuecomment-330858797.

**Comment by fulldecent** [comment]
SRI author signatures is definitely an interesting proposal. It trades away some security to make an easier implementation.

But as to whether SRI should be deployed wide-scale for all JS/CSS includes: absolutely, this is a best practice. [We have implemented it](https://github.com/gjtorikian/html-proofer/issues/382) in https://github.com/gjtorikian/html-proofer/ as a test for continuous integration. The big exceptions right now are Facebook, Twitter, and Google social/analytics extensions. Surprise, these are from companies where their visitors are the products. And Google Fonts is a special case where they are doing something really fancy. But don't worry, we already [have an issue open for that](https://github.com/google/fonts/issues/473). The jQueries / Bootstrap and 90%+ of other includes out there are already supporting SRI.

As an example see jQuery CDN at https://code.jquery.com/ if you click on the asset you want it gives you the CORS/SRI HTML code *by default* rather than just a URL.

**Comment by konklone** [comment]
> This is a very economical "review" that protects against the most likely and least detectable type of attack.

This kind of protection would only prevent an attack that was targeted to individual users. Are you suggesting this would detect network-level attacks, where google-analytics.com is being MITMed? Or an attack where Google has been compromised in order to get to a specific user?

In both cases, I wouldn't expect GSA hosting it to provide much protection -- if google-analytics.com can be MITMed, then likely so can dap.digitalgov.gov, and if the target was worth penetrating Google for then it would probably be worth penetrating GSA for.

**Comment by fulldecent** [comment]
GSA hosting provides better protection against existing risks:

* US government controls the GSA network (theoretically); but google-analytics.js is not accountable to the USG.
* Currently USG is vulnerable to infiltration of bad actors into Google, Facebook, Twitter, Visistat, Weibo, and other random organizations on the internet. GSA hosting reduces this vulnerability.

**Comment by fulldecent** [comment]
The easiest way to provide a reasonable security boost here is this security practice:

- Automatically download Google's analytics JS file to GSA servers each day.
- Notify staff if it is different than the day before.
- When notified, staff use a different IP address to manually download that file, and confirm the same file is accessible from different IP addresses (this is the approach used in the https://certificate.transparency.dev/ project).
- Staff briefly check the front page of the New York Times to see if millions of websites got hacked today.
- Staff replaces the GSA version with the new version.

This can be applied for the Google Analytics snippet, and any other JavaScript script.

Then GSA's recommended security posture will upgrade to:

1. Use SRI; or
2. Use the GSA hosted file without SRI; or
3. Don't use SRI, use the hot version hosted randomly on the internet, and then document in the project notes that this website is fully at risk to be compromised, with plausible deniability, and list the entities on that risk boundary.

This is exactly like have a 5 second buffer on live TV. It protects against, internet-wide attacks, mistakes, targeted attacks.

**Comment by levinmr** [comment]
SRI recommendations are on the DAP team's roadmap for security improvements.  Thanks for the suggestions, and stay tuned for updates

**Comment by konklone** [comment]
@levinmr Can you describe how SRI is planned to fit into DAP's support for self-hosting and central hosting? From a security perspective, SRI is functionally equivalent to self-hosting (and I would think would necessitate hosting many frozen versioned copies of the JS, as opposed to one central script), for reasons I described earlier in the thread.

There are other security (and privacy) concerns to weigh in allowing a proliferation of dead and outdated versions of DAP littered throughout the federal landscape, so I would hope that these are being considered in the analysis as well.
